jobs:
  build:
    environment:
      IMAGE_NAME: swathithangaraj/building-on-ci
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - kube-orb/install
        # - kube-orb/create-or-update-resource:
        #get-rollout-status: true
        #resource-file-path: root/swathi/deployment.yaml
        #resource-name: deployment/image_deployment
        #show-kubectl-command: true
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: sudo docker build -t $IMAGE_NAME:latest .
      - run:
           name: Publish Docker Image to Docker Hub
           command: |
             echo "123cbe!@#" | sudo docker login -u "swathithangaraj" --password-stdin
               sudo docker push $IMAGE_NAME:latest
               # deploy:
               #machine:
               #enabled: true
               #steps:
      - run:
          name: Deploy on k8s
          command: |
             kubectl --server=https://10.128.0.36:6443 --username=kubernetes-admin --client-key=/root/.kube/config create -f root/swathi/deployment.yaml
                  #kubectl config set-cluster demo-cluster --server=http://34.71.64.113:8080
                  # kubectl config set-context demo-system --cluster=demo-cluster
                  #kubectl config use-context demo-system
                  # kubectl get nodes


orbs:
  kube-orb: circleci/kubernetes@0.11.0
version: 2.1
workflows:
   version: 2.1
   build-deploy:
     jobs:
       - build:
               #- deploy:
               #requires:
               #- build
           filters: 
             branches: 
               only: master

